nnajhs:
  name: 'American Jewish Historical Society'
  description: ''
  building: ''
  address1:  'Center for Jewish History'
  address2: '15 West 16th Street'
  city:  'New York'
  state: 'NY'
  zip: '10011'
  country: 'United States'
  phone: '212-294-8350'
  contact_info: 'reference@ajhs.org'
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nnajhs.png'
nnan:
  name: 'American Numismatic Society'
  description: ''
  building: ''
  address1:  '75 Varick Street, 11th floor'
  address2: ''
  city:  'New York'
  state: 'NY'
  zip: '10013'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nnan.png'
nanb:
  name: 'Bard College Archives'
  description: ''
  building: 'Stevenson Library'
  address1:  '1 Library Road'
  address2: ''
  city:  'Annandale-on-Hudson'
  state: 'NY'
  zip: '12504'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nanb.png'
nybxlhr:
  name: 'Bronxville History Center'
  description: ''
  building: ''
  address1:  '201 Pondfield Rd. Bronxville'
  address2: ''
  city:  'Bronxville'
  state: 'NY'
  zip: '10708'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nybxlhr.png'
nyblhs:
  name: 'Brooklyn Historical Society'
  description: ''
  building: ''
  address1:  '128 Pierrepont Street'
  address2: ''
  city:  'Brooklyn'
  state: 'NY'
  zip: '11201'
  country: 'United States'
  phone: '718-222-4111'
  contact_info: 'library@brooklynhistory.org'
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nyblhs.png'
nybubpa:
  name: 'Burchfield Penney Art Center'
  description: ''
  building: ''
  address1:  '1300 Elmwood Avenue'
  address2: ''
  city:  'Buffalo'
  state: 'NY'
  zip: '14222'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nybubpa.gif'
nbucc:
  name: 'Canisius College'
  description: ''
  building: ''
  address1:  '2001 Main Street'
  address2: ''
  city:  'Buffalo'
  state: 'NY'
  zip: '14208'
  country: 'United States'
  phone: '(716) 883-7000'
  contact_info: 'info@canisius.edu'
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nbucc.png'
nynycjh:
  name: 'Center for Jewish History'
  description: ''
  building: 'Leo Baeck Institute'
  address1:  'Center for Jewish History'
  address2: '15 West 16th Street'
  city:  'New York'
  state: 'NY'
  zip: '10011'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nynycjh.png'
nhc:
  name: 'Colgate University'
  description: ''
  building: 'Case Library'
  address1:  '13 Oak Drive'
  address2: ''
  city:  'Hamilton'
  state: 'NY'
  zip: '13346'
  country: 'United States'
  phone: '315-228-6175'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nhc.jpg'
nalcsr:
  name: 'College of Saint Rose'
  description: ''
  building: ''
  address1:  '432 Western Avenue'
  address2: ''
  city:  'Albany'
  state: 'NY'
  zip: '12203'
  country: 'United States'
  phone: '1-800-637-8556'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nalcsr.png'
nncm:
  name: 'Columbia University Medical Center'
  description: ''
  building: ''
  address1:  '630 West 168th Street'
  address2: ''
  city:  'New York'
  state: 'NY'
  zip: '10032'
  country: 'United States'
  phone: '212-305-2862'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nncm.png'
nic:
  name: 'Cornell University, also known as Cornell University, State Colleges of Agriculture and Economics'
  description: ''
  building: ''
  address1:  '215 Garden Avenue'
  address2: ''
  city:  'Ithaca'
  state: 'NY'
  zip: '14853'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nic.gif'
nnepeml:
  name: 'Elting Memorial Library'
  description: ''
  building: ''
  address1:  '93 Main Street'
  address2: ''
  city:  'New Paltz'
  state: 'NY'
  zip: '12561'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nnepeml.jpg'
nysyecm:
  name: 'Erie Canal Museum'
  description: ''
  building: ''
  address1:  '318 Erie Boulevard East'
  address2: ''
  city:  'Syracuse'
  state: 'NY'
  zip: '13202'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nysyecm.png'
nycoofam:
  name: 'Fenimore Art Museum'
  description: ''
  building: ''
  address1:  '5798 State Highway 80'
  address2: ''
  city:  'Cooperstown'
  state: 'NY'
  zip: '13326'
  country: 'United States'
  phone: '607-547-1400'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nycoofam.jpg'
nyhdu:
  name: 'Foundation of Russian History'
  description: ''
  building: ''
  address1:  '1407 Robinson Road'
  address2: ''
  city:  'Jordanville'
  state: 'NY'
  zip: '13361'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nyhdu.png'
nnfr:
  name: 'Frick Art Reference Library'
  description: ''
  building: ''
  address1:  '10 E 71st St'
  address2: ''
  city:  ' New York'
  state: 'NY'
  zip: '10021'
  country: 'United States'
  phone: '(212) 547-0641'
  contact_info: 'library@frick.org'
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nnfr.png'
nnmec:
  name: 'General Society of Mechanics and Tradesmen of the City of New York'
  description: ''
  building: ''
  address1:  ' 20 West 44th Street'
  address2: ''
  city:  'New York'
  state: 'NY'
  zip: '10036'
  country: 'United States'
  phone: '212.840.1840'
  contact_info: 'victoria.dengel@generalsociety.org'
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nnmec.png'
nrge:
  name: 'George Eastman Museum'
  description: ''
  building: ''
  address1:  ''
  address2: ''
  city:  ''
  state: 'NY'
  zip: '0'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/ead_logo.gif'
noneoc:
  name: 'Hartwick College'
  description: ''
  building: ''
  address1:  'P.O. Box 4022'
  address2: ''
  city:  'Oneonta'
  state: 'NY'
  zip: '13820'
  country: 'United States'
  phone: '607-431-4000'
  contact_info: 'museum@hartwick.edu'
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/noneoc.jpg'
nykihrm:
  name: 'Hudson River Maritime Museum'
  description: ''
  building: ''
  address1:  '50 Rondout Landing'
  address2: ''
  city:  'Kingston'
  state: 'NY'
  zip: '12401'
  country: 'United States'
  phone: '​845-338-0071'
  contact_info: 'info@hrmm.org'
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nykihrm.jpg'
nyhutca:
  name: 'Huntington Town Clerk Archives'
  description: ''
  building: ''
  address1:  '100 Main Street'
  address2: ''
  city:  'Huntington'
  state: 'NY'
  zip: '11743'
  country: 'United States'
  phone: '(631) 351-3000'
  contact_info: 'amattheou@huntingtonNY.gov'
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nyhutca.png'
npkmc:
  name: 'Marist College'
  description: ''
  building: ''
  address1:  '3399 North Road'
  address2: ''
  city:  'Poughkeepsie'
  state: 'NY'
  zip: '12601'
  country: 'United States'
  phone: '845-575-3000'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/npkmc.png'
nbum:
  name: 'Medaille College'
  description: ''
  building: ''
  address1:  '18 Agassiz Circle'
  address2: ''
  city:  'Buffalo'
  state: 'NY'
  zip: '14214'
  country: 'United States'
  phone: '(716) 880-2000'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nbum.png'
nnmm:
  name: 'Metropolitan Museum of Art'
  description: ''
  building: ''
  address1:  '1000 Fifth Avenue'
  address2: ''
  city:  'New York'
  state: 'NY'
  zip: '10028'
  country: 'United States'
  phone: '212-535-7710'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nnmm.jpg'
nyschmis:
  name: 'Museum of Innovation and Science'
  description: ''
  building: ''
  address1:  '5 Nott Terrace Heights'
  address2: ''
  city:  'Schenectady'
  state: 'NY'
  zip: '12308'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nyschmis.png'
nnmoma:
  name: 'Museum of Modern Art'
  description: ''
  building: ''
  address1:  '11 West 53 Street'
  address2: ''
  city:  'New York'
  state: 'NY'
  zip: '10019'
  country: 'United States'
  phone: '(212) 708-9433'
  contact_info: 'library@moma.org'
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nnmoma.jpg'
nn:
  name: 'New York Public Library'
  description: ''
  building: 'Stephen A. Schwarzman Building'
  address1:  'Fifth Avenue & 42nd Street'
  address2: ''
  city:  'New York'
  state: 'NY'
  zip: '10018'
  country: 'United States'
  phone: ' 917-ASK-NYPL'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nn.jpg'
nlocknhi:
  name: 'Niagara County History Center'
  description: ''
  building: ''
  address1:  '215 Niagara St.'
  address2: ''
  city:  'Lockport'
  state: 'NY'
  zip: '14094'
  country: 'United States'
  phone: '716-434-7433'
  contact_info: 'info@niagarahistory.org'
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nlocknhi.png'
nnia:
  name: 'Niagara Falls Public Library'
  description: ''
  building: 'EARL W. BRYDGES BUILDING'
  address1:  '1425 Main Street'
  address2: ''
  city:  'Niagara Falls'
  state: 'NY'
  zip: '14305'
  country: 'United States'
  phone: ' (716) 286-4894'
  contact_info: 'nflref@nioga.org'
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nnia.jpg'
nsyoc:
  name: 'Onondaga Community College'
  description: ''
  building: ''
  address1:  '4585 West Seneca Turnpike'
  address2: ''
  city:  'Syracuse'
  state: 'NY'
  zip: '13215'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nsyoc.jpg'
nnod:
  name: 'Oskar Diethelm Library'
  description: ''
  building: 'DeWitt Wallace Institute of Psychiatry: History, Policy and the Arts'
  address1:  'Weill Cornell Medical College'
  address2: '525 East 68th Street, Box 140'
  city:  'New York'
  state: 'NY'
  zip: '10065'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nnod.jpg'
nrri:
  name: 'Rochester Institute of Technology'
  description: ''
  building: ''
  address1:  ' One Lomb Memorial Dr.'
  address2: ''
  city:  'Rochester'
  state: 'NY'
  zip: '14623'
  country: 'United States'
  phone: ' 585-475-2411'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nrri.png'
nnttr:
  name: 'Rockefeller Archive Center'
  description: ''
  building: ''
  address1:  '15 Dayton Avenue'
  address2: ''
  city:  'Sleepy Hollow'
  state: 'NY'
  zip: '10591'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nnttr.png'
nysspl:
  name: 'Saratoga Springs Public Library'
  description: ''
  building: ''
  address1:  '49 Henry Street'
  address2: ''
  city:  'Saratoga Springs'
  state: 'NY'
  zip: '12866'
  country: 'United States'
  phone: '1-518-584-7860'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nysspl_logo.jpg'
nschchi:
  name: 'Schenectady County Historical Society'
  description: ''
  building: ''
  address1:  ' 32 Washington Ave.'
  address2: ''
  city:  'Schenectady'
  state: 'NY'
  zip: '12305'
  country: 'United States'
  phone: ' 518 374 0263'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nschchi.jpg'
nalsu:
  name: 'State University of New York at Albany'
  description: 'Can talk about the repository here'
  building: 'M. E. Grenander Department of Special Collections & Archives'
  address1:  'Science Library 350'
  address2: '1400 Washington Ave'
  city:  'Albany'
  state: 'NY'
  zip: '12222'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: 'can put a note about visits'
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nalsu_logo.png'
nbuumu:
  name: 'State University of New York at Buffalo. Music Library'
  description: ''
  building: ''
  address1:  '112 Baird Hall'
  address2: ''
  city:  'Buffalo'
  state: 'NY'
  zip: '14260'
  country: 'United States'
  phone: '716-645-2924'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nbuumu.png'
nfredu:
  name: 'State University of New York at Fredonia'
  description: ''
  building: ''
  address1:  '280 Central Ave.'
  address2: ''
  city:  'Fredonia'
  state: 'NY'
  zip: '14063'
  country: 'United States'
  phone: '716-673-3111'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nfredu.jpg'
nosu:
  name: 'State University of New York at Oswego'
  description: ''
  building: 'Penfield Library'
  address1:  '7060 State Route 104'
  address2: ''
  city:  'Oswego'
  state: 'NY'
  zip: '13126'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nosu.jpg'
nbuc:
  name: 'State University of New York, College at Buffalo'
  description: ''
  building: 'E. H. Butler Library'
  address1:  'Room 214'
  address2: '1300 Elmwood Ave'
  city:  'Buffalo'
  state: 'NY'
  zip: '14222'
  country: 'United States'
  phone: '716-878-6304'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nbuc.png'
nysim:
  name: 'Staten Island Museum'
  description: ''
  building: 'Building A'
  address1:  '1000 Richmond Terrace'
  address2: ''
  city:  'Staten Island'
  state: 'NY'
  zip: '10301'
  country: 'United States'
  phone: '718.727.1135'
  contact_info: 'info@statenislandmuseum.org'
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nysim.gif'
nsyu:
  name: 'Syracuse University'
  description: 'Can include a repository description here.'
  building: 'Special Collections Research Center'
  address1:  'Syracuse University Libraries'
  address2: 'Bird Library, Room 600'
  city:  'Syracuse'
  state: 'NY'
  zip: '13244'
  country: 'United States'
  phone: '315.443.2697'
  contact_info: 'scrc@syr.edu'
  visit_note: 'Can include a visitation note here.'
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nsyu.png'
nsyul:
  name: 'Syracuse University College of Law'
  description: ''
  building: ' Dineen Hall '
  address1:  ' 950 Irving Avenue'
  address2: ''
  city:  'Syracuse'
  state: 'NY'
  zip: '13244'
  country: 'United States'
  phone: ''
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nsyul.png'
nbuhi:
  name: 'The Buffalo History Museum'
  description: ''
  building: ''
  address1:  '1 Museum Court'
  address2: ''
  city:  'Bufalo'
  state: 'NY'
  zip: '14216'
  country: 'United States'
  phone: '716-873-9644 ex'
  contact_info: 'library@buffalohistory.org'
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nbuhi.jpg'
nru:
  name: 'University of Rochester'
  description: ''
  building: ''
  address1:  '500 Joseph C. Wilson Boulevard'
  address2: ''
  city:  'Rochester'
  state: 'NY'
  zip: '14627'
  country: 'United States'
  phone: '(585) 275-2121'
  contact_info: ''
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nru.jpg'
nwhp:
  name: 'White Plains Public Library'
  description: ''
  building: ''
  address1:  '100 Martine Ave.'
  address2: ''
  city:  'White Plains'
  state: 'NY'
  zip: '10601'
  country: 'United States'
  phone: '914-422-1400'
  contact_info: 'librarian@whiteplainslibrary.org'
  visit_note: ''
  thumbnail_url: '/sites/www.empireadc.org/files/repo_logos/nwhp.png'
